name:                morse
version:             0.1.0.0
github:              "randallalexander/morse"
license:             BSD3
author:              "Randall Alexander"
maintainer:          "randall.alexander@example.com"
copyright:           "Copyright: (c) 2016 Randall Alexander"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Learning Project

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/randallalexander/morse#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  morse:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse

tests:
  morse-test:
    main:                Spec.hs
    source-dirs:         tests
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - morse
